wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.15.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687534472.024294
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.9.6
      5: 0.15.4
      8:
      - 4
      - 5
